Still getting the error:
FirebaseError: Missing or insufficient permissions.
    at resolveErrorDev (https://6000-idx-studio-1746460064871.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17582:48)
    at processFullStringRow (https://6000-idx-studio-1746460064871.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17798:23)
    at processFullBinaryRow (https://6000-idx-studio-1746460064871.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17786:9)
    at progress (https://6000-idx-studio-1746460064871.cluster-ux5mmlia3zhhask7riihruxydo.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:17932:102)